spring:
  application:
    name: Orders

  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: ecom_user
    password: ecom_user

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

server:
  port: 8083
