spring:
  application:
    name: users

  mongodb:
    uri: mongodb://localhost:27017/users_db
#    uri: ${MONGODB_URI}


#  datasource:
#    url: jdbc:postgresql://localhost:5432/users_db
#    username: ecom_user
#    password: ecom_user
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.jdbc.time_zone: UTC


server:
  port: 8082


